[package]
name = "cargo-show-asm"
version = "0.2.13"
edition = "2021"
description = "A cargo subcommand that displays the generated assembly of Rust source code."
categories = ["development-tools::cargo-plugins", "development-tools::debugging" ]
keywords = ["assembly", "plugins", "cargo"]
repository = "https://github.com/pacak/cargo-show-asm"
homepage = "https://github.com/pacak/cargo-show-asm"
authors = [ "Michael Baykov <manpacket@gmail.com>" ]
readme = "README.md"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1"
#bpaf = { version = "0.7.7", features = ["bpaf_derive", "autocomplete", "manpage"], path = "../bpaf" }
bpaf = { git = "https://github.com/pacak/bpaf", branch = "semantic", features = ["bpaf_derive", "autocomplete", "manpage"] }
#bpaf = { path = "../bpaf", features = ["bpaf_derive", "autocomplete", "manpage"] }
cargo_metadata = "0.15.2"
line-span = "0.1"
nom = "7"
once_cell = "1"
owo-colors = { version = "3", features = ["supports-colors"] }
regex = "1"
rustc-demangle = "0.1"
same-file = "1.0.6"
supports-color = "2.0"

[target.'cfg(target_family = "unix")'.dependencies]
nix = { version = "0.26", default-features = false, features = ["signal"] }

[features]
bright-color = ["bpaf/bright-color"]
dull-color = ["bpaf/dull-color"]

[[bin]]
name = "cargo-asm"
path = "src/main.rs"

[workspace.metadata.cauwugo]
bpaf = true
